# Generated by Django 4.2.6 on 2023-10-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunderasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasse', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Rassen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hundename', models.CharField(max_length=200)),
                ('birth', models.DateField(blank=True, null=True)),
                ('versichertennummer', models.BooleanField(default=False)),
                ('besonderheiten', models.CharField(blank=True, max_length=800, null=True)),
                ('name', models.CharField(max_length=200)),
                ('vorname', models.CharField(max_length=200)),
                ('tel', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=20)),
                ('ort', models.CharField(max_length=300)),
                ('Rasse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hunderasse')),
            ],
            options={
                'verbose_name_plural': 'Kunden',
            },
        ),
        migrations.CreateModel(
            name='Bilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bild', models.FileField(upload_to='')),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kunde')),
            ],
            options={
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.CreateModel(
            name='Bemerkungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=8000)),
                ('taetigkeit', models.BooleanField(default=True)),
                ('kunde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kunde')),
            ],
            options={
                'verbose_name_plural': 'Bemerkungen',
            },
        ),
    ]
