# Generated by Django 4.2.6 on 2023-10-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilder',
            name='anzeigebild',
            field=models.BooleanField(default=False),
        ),
    ]
